const toPDF = require("custom-soffice-to-pdf");
const whatsbixby = require('../events');
const { MessageType, Mimetype } = require(Wa-Web);
const got = require('got');
const ffmpeg = require('fluent-ffmpeg');
const Config = require('../config');


Asena.addCommand({pattern: 'topdf ?(.*)', fromMe: false, desc: 'convert img-pdf' , dontAddCommandList: true }, async (message, client) => {


if (!message.reply_message)
      return await client.sendMessage('reply to image');
    if (message.reply_message.audio || message.reply_message.video || message.reply_message.sticker || message.reply_message.pdf) return message.sendMessage('NOT_SUPPORTED');
     
   var location = await message.client.downloadAndSaveMediaMessage({
            key: {
                remoteJid: message.reply_message.jid,
                id: message.reply_message.id
            },
            message: message.reply_message.data.quotedMessage
        });
   
      ffmpeg(location)
                .save('st.pdf')
                .on('end', async () => {
                  
   
         await client.sendMessage(message.jid,fs.readFileSync('st.pdf'),  MessageType.document , {
            filename: 'generated by WhatsBixby ' + ".pdf",
            mimetype: Mimetype.pdf,quoted: message.data
          });
      },
      (err) => console.log(`topdf : ${err}`)
    );
  }

);

